module.exports.registerUser = require('./registerUser.controller')
module.exports.login = require('./login.controller')
module.exports.verifyEmail = require('./verifyEmail.controller')
module.exports.resendVerifycationEmail = require('./resendVerifycationEmail.controller.js')
module.exports.getAllUsers = require('./getAllUsers.controller.js')
module.exports.getLeaderboard = require('./getLeaderboard.controller.js')
module.exports.forgotPassword = require('./forgotPassword.controller.js')
module.exports.sendForgotOtp = require('./sendForgotOtp.controller.js')
module.exports.sendResetLink = require('./sendResetLink.controller.js')
module.exports.getReffredUsers = require('./getReffredUsers.controller.js')
module.exports.updateUserStatus = require('./updateUserStatus.controller.js')

