module.exports.addGames = require('./addgames.service')
module.exports.getAllGames = require('./getAllGames.service')
module.exports.getAllGamesAdmin = require('./getAllGamesAdmin.service.js')
module.exports.deleteGame = require('./deleteGame.service.js')
module.exports.updateGame = require('./updateGame.service.js')
module.exports.getPrivateGameAdmin = require('./getPrivateGameAdmin.service.js')